# Generated by Django 3.2.3 on 2021-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camilo',
            fields=[
                ('idCamilo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de camilo')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre de camilo')),
            ],
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('idEdad', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Edad')),
                ('Edad', models.CharField(max_length=3, verbose_name='Edad')),
            ],
        ),
    ]
