# Generated by Django 3.2.3 on 2021-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_formulario_persona_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_persona',
            name='edad',
            field=models.IntegerField(verbose_name='Edad de la persona'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut de la persona sin punto ni guion'),
        ),
    ]
