# Generated by Django 3.2.3 on 2021-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210527_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_bicicletas',
            name='rango_edad_uso',
            field=models.CharField(max_length=20, verbose_name='Rango de la edad que pueden usar este tipo de bicicletas'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='sexo',
            field=models.CharField(max_length=50, verbose_name='Sexo de la persona'),
        ),
    ]
