# Generated by Django 3.2.3 on 2021-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210527_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulario_Bicicletas',
            new_name='bicicleta',
        ),
        migrations.RenameModel(
            old_name='Formulario_disciplina',
            new_name='disciplina',
        ),
        migrations.RenameModel(
            old_name='Formulario_Persona',
            new_name='Persona',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='Formulario_Bicicletas',
            new_name='bicicleta',
        ),
    ]
