# Generated by Django 3.2.3 on 2021-05-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210527_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='disciplina',
            new_name='Disciplina',
        ),
    ]
