# Generated by Django 3.2.3 on 2021-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_disciplina_disciplina_disciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='bicicleta',
            new_name='tipo_bicicleta',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(max_length=60, verbose_name='Tipo de bicicleta'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=30, verbose_name='Sexo de la persona'),
        ),
    ]
