# Generated by Django 3.2.3 on 2021-05-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_tipo_bicicleta_disciplina_bicicleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_Bicicletas',
            fields=[
                ('idTipo_bicicleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de bicicleta')),
                ('tipo_bicicleta', models.CharField(max_length=70, verbose_name='Tipo de bicicleta')),
                ('rango_edad_uso', models.CharField(max_length=30, verbose_name='Rango de la edad que pueden usar este tipo de bicicletas')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_disciplina',
            fields=[
                ('idDisciplina', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la disciplina')),
                ('disciplina', models.CharField(max_length=70, verbose_name='Disciplina de la bicicleta')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de la disciplina')),
                ('Formulario_Bicicletas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formulario_bicicletas')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Persona',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut de la persona sin punto ni guion')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre de la persona')),
                ('Apellido_paterno', models.CharField(max_length=50, verbose_name='apellido paterno de la persona')),
                ('Apellido_materno', models.CharField(max_length=50, verbose_name='apellido materno de la persona')),
                ('edad', models.IntegerField(verbose_name='Edad de la persona')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo de la persona')),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='bicicleta',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='bicicleta',
        ),
        migrations.DeleteModel(
            name='disciplina',
        ),
    ]
