# Generated by Django 3.2.3 on 2021-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210527_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_persona',
            name='Apellido_materno',
            field=models.CharField(max_length=50, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='Apellido_paterno',
            field=models.CharField(max_length=50, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='edad',
            field=models.IntegerField(verbose_name='Edad '),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut sin punto ni guion'),
        ),
        migrations.AlterField(
            model_name='formulario_persona',
            name='sexo',
            field=models.CharField(max_length=50, verbose_name='Sexo'),
        ),
    ]
