# Generated by Django 3.2.3 on 2021-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210530_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=80, verbose_name='apellidos')),
                ('correo', models.CharField(max_length=100, verbose_name='correo')),
                ('contrasenia', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
        ),
    ]
