# Generated by Django 3.2.3 on 2021-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellidos',
            field=models.CharField(max_length=70, verbose_name='apellidos'),
        ),
    ]
