# Generated by Django 3.2.3 on 2021-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_registro_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellidos',
            field=models.CharField(max_length=80, verbose_name='apellidos'),
        ),
    ]
