# Generated by Django 3.2.3 on 2021-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_registro_apellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.CharField(max_length=90, verbose_name='correo'),
        ),
    ]
