# Generated by Django 3.2.3 on 2021-06-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210601_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Nombre',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellidos',
            field=models.CharField(max_length=70, verbose_name='apellidos'),
        ),
    ]
