# Generated by Django 3.2.3 on 2021-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_registro_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_persona',
            name='Apellido_paterno',
            field=models.CharField(max_length=40, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellidos',
            field=models.CharField(max_length=70, verbose_name='apellidos'),
        ),
    ]
